### ISSUE TITLE
Конфликт команд

### ISSUE THREAD

**Issue by krsnv** [Viktoriya-dem/nx_bootcamp_nix_diary#1]
https://github.com/Viktoriya-dem/nx_bootcamp_nix_diary/blob/eb4f1f7191d81966f6aed928ac4da7bc40fc9455/diary.sh#L5

Имена команд лучше всего держать в собственном неймспейсе, т. к. могут быть пересечения с глобальными командами bash shell. 

Ситуацию можно быстро исправить добавив `diary-` ко всем командам.

**Comment by Viktoriya-dem** [comment]
Done
