### ISSUE TITLE
Исправить рекурсивный поиск без явного указания каталога дневника

### ISSUE THREAD

**Issue by krsnv** [Viktoriya-dem/nx_bootcamp_nix_diary#10]
https://github.com/Viktoriya-dem/nx_bootcamp_nix_diary/blob/eb4f1f7191d81966f6aed928ac4da7bc40fc9455/diary.sh#L57

Суть похожа на: https://github.com/Viktoriya-dem/nx_bootcamp_nix_diary/issues/6

**Comment by Viktoriya-dem** [comment]
Done
