### ISSUE TITLE
Нормализовать имена функций

### ISSUE THREAD

**Issue by krsnv** [Viktoriya-dem/nx_bootcamp_nix_diary#12]
https://github.com/Viktoriya-dem/nx_bootcamp_nix_diary/blob/eb4f1f7191d81966f6aed928ac4da7bc40fc9455/diary.sh#L141

Сейчас используется то camelCase, то low-case. Нужно что-то удобно. Лучше второе. Посмотри как имеются команды в приложения cli.

**Comment by Viktoriya-dem** [comment]
Done
