### ISSUE TITLE
Указать путь, в котором выполняется поиск файлов

### ISSUE THREAD

**Issue by krsnv** [Viktoriya-dem/nx_bootcamp_nix_diary#6]
https://github.com/Viktoriya-dem/nx_bootcamp_nix_diary/blob/eb4f1f7191d81966f6aed928ac4da7bc40fc9455/diary.sh#L29

Сейчас идет поиск рекурсивно по всем каталогам относительно текущей директории. Это может вызвать множество проблем и, что важно, будет собирать по всей файловой системе все файлы *.md. А ведь нам это не нужно, верно?

**Comment by Viktoriya-dem** [comment]
Done
